@echo off
set PATH=
set PATH=%PATH%;C:\tools\jdk-17.0.8_7\bin
REM set PATH=%PATH%;C:\tools\bin
set PATH=%PATH%;C:\tools\git\cmd
set PATH=%PATH%;C:\tools\git\mingw64\bin
set PATH=%PATH%;C:\tools\git\usr\bin
set PATH=%PATH%;C:\tools\vs_code\bin
REM set PATH=%PATH%;C:\tools\vim\vim82
set PATH=%PATH%;C:\tools\WinMerge
set PATH=%PATH%;C:\Users\JonNewton\AppData\Local\Programs\Python\Python311\Scripts\
set PATH=%PATH%;C:\Users\JonNewton\AppData\Local\Programs\Python\Python311\
set PATH=%PATH%;C:\Users\JonNewton\.deno\bin
set PATH=%PATH%;C:\tools\SmartGit\bin
set PATH=%PATH%;C:\tools\PuTTY\
set PATH=%PATH%;C:\tools\nodejs\
set PATH=%PATH%;C:\work\code\udm\DevOps\GuiBuild\bin
set PATH=%PATH%;C:\tools\sonar-scanner-4.7.0.2747-windows\bin
set PATH=%PATH%;C:\tools\build-wrapper-win-x86
set PATH=%PATH%;C:\Users\JonNewton\AppData\Roaming\npm
set PATH=%PATH%;C:\Users\JonNewton\AppData\Local\Microsoft\WindowsApps
set PATH=%PATH%;C:\Windows\System32\OpenSSH\
set PATH=%PATH%;C:\Program Files (x86)\dotnet\
set PATH=%PATH%;C:\Program Files\dotnet\
set PATH=%PATH%;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
set PATH=%PATH%;C:\Windows\System32\WindowsPowerShell\v1.0\
set PATH=%PATH%;C:\Windows
set PATH=%PATH%;C:\Windows\system32
set PATH=%PATH%;C:\Windows\System32\Wbem
set PATH=%PATH%;C:\Program Files\SafeNet\Authentication\SAC\x64
set PATH=%PATH%;C:\Program Files\SafeNet\Authentication\SAC\x32
set PATH=%PATH%;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
set PATH=%PATH%;C:\Program Files\PowerShell\7\
set PATH=%PATH%;C:\Program Files\Docker\Docker\resources\bin
set PATH=%PATH%;C:\Users\JonNewton\.cargo\bin
set PATH=%PATH%;C:\Users\JonNewton\AppData\Roaming\npm
set PATH=%PATH%;C:\Program Files (x86)\Nmap
set PATH=%PATH%;C:\tools\terminal-1.18.2681.0
set PATH=%PATH%;C:\tools\Neovim\bin
set PATH=%PATH%;C:\tools\code_signing
set PATH=%PATH%;C:\tools\mantis
set PATH=%PATH%;C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin
set PATH=%PATH%;C:\Users\JonNewton\AppData\Local\Programs\Python\Python311\Scripts\
set PATH=%PATH%;C:\Users\JonNewton\AppData\Local\Programs\Python\Python311\
set PATH=%PATH%;C:\Users\JonNewton\AppData\Local\Microsoft\WinGet\Links
